### ISSUE TITLE
Build.sh -buildtests flag

### ISSUE THREAD

**Issue by cpa750** [ntu-sdi/dataset-labelling-tool#16]
Can we get a -buildtests flag added to build.sh as building the whole project after just changing the tests takes too long.

**Comment by ivica3730k** [comment]
Because of test requiring files created which are generated by compiling the main code, building the test requires rebuilding the whole solution.

However, if you don't make any changes to main code, your compiler should not be rebuilding main code from scratch, only unit tests should be rebuilt.
First build
![Screenshot from 2020-03-03 15-00-13](https://user-images.githubusercontent.com/17437897/75788285-ebf1f380-5d5f-11ea-847d-5f9ecef8320a.png)
First build
![Screenshot from 2020-03-03 15-00-58](https://user-images.githubusercontent.com/17437897/75788288-ec8a8a00-5d5f-11ea-81c8-2332b3e8511a.png)
Rebuilding 2nd time
![Screenshot from 2020-03-03 15-01-34](https://user-images.githubusercontent.com/17437897/75788289-ed232080-5d5f-11ea-9a55-6fbfcd664431.png)
